language: node_js

# https://github.com/nodejs/LTS
node_js:
  - '6'

git:
  depth: 5

cache: yarn

before_install:
  - npm config set spin false --global

script:
  - npm run lint && npm test -- --coverage
  - coveralls < ./coverage/lcov.info
